import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const rootDir = process.cwd();
const packageJsonPath = path.join(rootDir, "package.json");
const packageLockPath = path.join(rootDir, "package-lock.json");
const cargoTomlPath = path.join(rootDir, "src-tauri", "Cargo.toml");
const tauriConfigPath = path.join(rootDir, "src-tauri", "tauri.conf.json");
const generatedVersionPath = path.join(rootDir, "src", "generated", "app-version.ts");

const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
const appVersion = packageJson.version;

if (typeof appVersion !== "string" || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(appVersion)) {
  throw new Error(`Invalid package.json version: ${String(appVersion)}`);
}

await syncPackageLock(appVersion);
await syncCargoToml(appVersion);
await syncTauriConfig(appVersion);
await syncGeneratedFrontendVersion(appVersion);

console.log(`Synced Orion version to ${appVersion}`);

async function syncPackageLock(version) {
  const packageLock = JSON.parse(await readFile(packageLockPath, "utf8"));

  packageLock.version = version;

  if (packageLock.packages?.[""]) {
    packageLock.packages[""].version = version;
  }

  await writeIfChanged(packageLockPath, `${JSON.stringify(packageLock, null, 2)}\n`);
}

async function syncCargoToml(version) {
  const cargoToml = await readFile(cargoTomlPath, "utf8");
  const nextCargoToml = cargoToml.replace(
    /^version = ".*"$/m,
    `version = "${version}"`,
  );

  if (cargoToml === nextCargoToml) {
    return;
  }

  await writeFile(cargoTomlPath, nextCargoToml, "utf8");
}

async function syncTauriConfig(version) {
  const tauriConfig = JSON.parse(await readFile(tauriConfigPath, "utf8"));
  tauriConfig.version = version;

  await writeIfChanged(tauriConfigPath, `${JSON.stringify(tauriConfig, null, 2)}\n`);
}

async function syncGeneratedFrontendVersion(version) {
  await mkdir(path.dirname(generatedVersionPath), { recursive: true });

  const fileContents = `// Auto-generated by scripts/sync-version.mjs. Do not edit manually.\nexport const appVersion = "${version}" as const;\n`;

  await writeIfChanged(generatedVersionPath, fileContents);
}

async function writeIfChanged(filePath, nextContents) {
  let currentContents = "";

  try {
    currentContents = await readFile(filePath, "utf8");
  } catch (error) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") {
      throw error;
    }
  }

  if (currentContents === nextContents) {
    return;
  }

  await writeFile(filePath, nextContents, "utf8");
}
